package com.divt.attendance.android.model;

public enum ResponseAPI {
  SUCCESS, // 0
  SERVER_ERROR, // 1 --> USED BY UI CALLBACK
  APP_VER_OBSOLETE, // 2
  TS_NOT_VALID, // 3
  HASH_NOT_MATCH, // 4
  DEV_MESSED_QUERY, // 5
  MAINTENANCE_STATE, // 6
  USER_UNREGISTERED, // 7
  USER_NOT_FOUND, // 8
  PERMISSION_ISSUE, // 9
  CREDENTIAL_EMPTY, // 10
  TOKEN_NOT_FOUND, // 11
  WRONG_PASSWORD, // 12
  ENTRY_NOT_FOUND, // 13
  ALREADY_USED, // 14
  USE_ANOTHER_VAL, // 15
  NO_CHANGES, // 16
  FILE_NOT_FOUND, // 17
  FILE_SIZE_TOO_BIG, // 18
  COUNT
}